wget -bc https://ftp.microbio.me/pub/QIIME-v1.5.0-dependencies/stamatak-standard-RAxML-5_7_2012.tgz
wget -bc https://occams.dfci.harvard.edu/pub/bio/tgi/software/cdbfasta/cdbfasta.tar.gz
wget -bc http://sourceforge.net/projects/microbiomeutil/files/__OLD_VERSIONS/microbiomeutil_2010-04-29.tar.gz
wget -bc https://ftp.microbio.me/pub/QIIME-v1.5.0-dependencies/cd-hit-2007-0131.tgz
wget -bc http://sourceforge.net/projects/rdp-classifier/files/rdp-classifier/rdp_classifier_2.2.zip
wget -bc https://ftp.ncbi.nlm.nih.gov/blast/executables/legacy.NOTSUPPORTED/2.2.22/blast-2.2.22-x64-linux.tar.gz
wget -bc http://www.drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux64.tar.gz
wget -bc http://eddylab.org/software/infernal/infernal-1.0.2.tar.gz
wget -bc http://chianti.ucsd.edu/Cyto-2_7_0/cytoscapeSource-v2.7.0.tar.gz
wget -bc http://bioinformatics.hungry.com/clearcut/clearcut-1.0.9.tar.gz
wget -bc https://ftp.microbio.me/pub/QIIME-v1.6.0-dependencies/mothur-1.25.0.tar.gz
wget -bc https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ampliconnoise/AmpliconNoiseV1.27.tar.gz
wget -bc http://www.tbi.univie.ac.at/RNA/packages/source/ViennaRNA-1.8.4.tar.gz
wget -bc http://sourceforge.net/projects/pprospector/files/pprospector-1.0.1.tar.gz
wget -bc http://static.davidsoergel.com/rtax-0.984.tgz
wget -bc https://github.com/MG-RAST/DRISEE/zipball/v1.2
wget -bc http://downloads.sourceforge.net/project/bio-bwa/bwa-0.6.2.tar.bz2
wget -bc http://hgwdev.cse.ucsc.edu/~kent/exe/linux/blatSuite.34.zip
wget -bc https://github.com/danknights/sourcetracker/archive/v1.0.zip
wget -bc https://downloads.sourceforge.net/project/tax2tree/tax2tree-v1.0.tar.gz
git clone git@github.com:qiime/qiime-galaxy.git
wget -bc https://bitbucket.org/galaxy/galaxy-dist/get/release_2013.01.13.tar.gz
wget -bc https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ea-utils/ea-utils.1.1.2-537.tar.gz
wget -bc https://github.com/jstjohn/SeqPrep/archive/v1.1.tar.gz
